server:
  port: 9211

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://mysql:3306/pastry-chat?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
  type-enums-package: com.mrl.pastry.chat.model.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler