server:
  port: 2862

springfox:
  documentation:
    enabled: false

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 2MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/pastry-upload?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
  type-enums-package: com.mrl.pastry.upload.model.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler